version: "3.8"

services:
  gkblog:
    build:
      context: .
      dockerfile: apps/gkBlog/Dockerfile
    image: gkblog:latest
    container_name: gkblog-red
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
